version: 0.2

env:
  variables:
     AWS_DEFAULT_REGION: "us-east-1"
     CODE_DEPLOY_S3_BUCKET: "ctni-backend-codedeploy-artifact"
  secrets-manager:
     AWS_ACCESS_KEY_ID: ctni-cli-creds:AWS_ACCESS_KEY_ID
     AWS_SECRET_ACCESS_KEY: ctni-cli-creds:AWS_SECRET_ACCESS_KEY
phases:
  install:
    commands:
      - apt-get update
      - echo entered install phase
      - echo Installing packages
      - apt-get install -y python3.6
      - apt install -y python3-pip
      - apt-get install zip unzip
      - echo installing aws cli
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - rm awscliv2.zip
      - ./aws/install
  build:
    commands:
      - pwd
      - ls
      - zip -r ctni-backend-${CODEBUILD_BUILD_NUMBER}.zip . -x ./aws/**\*
      - pwd
      - ls -al
  post_build:
    commands:
      - aws s3 cp ctni-backend-${CODEBUILD_BUILD_NUMBER}.zip s3://${CODE_DEPLOY_S3_BUCKET}